Project mobile first
Carl2678/microverse-project-portfolio-mobile-first pull request #4
Opened 2022-10-27 22:20 UTC by Carl2678

add the file on the repo.
- make fisrt commit
- Contributing to mobile-first project
- Watching the linters.yml is well configured
- build 2 section at the project
- configure Linters.yml

2022-10-27 23:29 UTC, fherrerao requested changes
Hi @Carl2678 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn`t have linters check 🌊 this [link](https://github.com/microverseinc/linters-config) to add it, the commit messages should be meaningful, and the name of the branch should represent an action 🐎.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 00:40 UTC, Bondok6 reviewed
## Hi @Carl2678 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Linter should be set up correctly for this repository.
- [ ] Linter result should be green, this means that the last commit have a green check mark (✅)
> 💡 To fix this issue
**The `workflows` should be a folder not a file**  and the `linters.yml` should be inside the `workflow` folder 👍


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 01:19 UTC, Gopxfs commented
# STATUS: INVALID REQUEST

Hi @Carl2678 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 🚨 Your project currently doesn't have any linters. To fix this, please update your '.github/workflows' folder name. It is missing the letter 'f':
![image](https://user-images.githubusercontent.com/42799579/198434658-9abb0e27-2fc7-45da-ad94-f7c48328f923.png)

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 08:29 UTC, Yazino12 reviewed
## Hi @Carl2678 🖐🏾,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

### To highlight:
- Good PR title ✔️
- Descriptive PR summary ✔️ 

# STATUS:  INVALID CODE REVIEW REQUEST ⛔⛔⛔

- [ ] You have submitted a project, that is using the wrong linter check, For this project, you should use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css) linters ✔.

- [ ] Please make sure to use correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) ✨

- [ ] From now on, try to write better commit messages. The sentences should be capitalized and in the imperative form. Example: "Add technologies to card" and not "my seconde commit" 👍🏽.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏🏾

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @Yazino12 when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_Invalid Code Review Request **does not** count into the code reviews limit._

2022-10-28 08:55 UTC, Carl2678 commented
> I used the instructions on this page step by step, I just forgot to add the CSS files

2022-10-28 09:56 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @Carl2678 
I'm sure you put a lot of effort into this project but this PR is invalid because Stylelint check is failing😓 

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 15:43 UTC, Alfredbis29 reviewed
Hi @Carl2678 ,

 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request :red_circle: 
 You have submitted a project, that doesn`t have linters check ocean this [link](https://github.com/microverseinc/linters-config) to add it, the commit messages should be meaningful, and the name of the branch should represent an action racehorse.
 
 Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
 
 Cheers and Happy coding! :clap: :clap: :clap:
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 17:48 UTC, Owusu-Desmond requested changes
Hi @Carl2678 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅

## Required Changes ♻️

_Check the comments under the review._

- [ ] Please your readme file is missing some sections like  `Acknowledgments`,`Contributing`, `Show your support`, and `License`. You can follow microverse readme [template](https://github.com/microverseinc/readme-template) to add these sections to your project readme.md file. :pray:
   
   `NOTE`: Some already added sections are not well structured. Please kindly make sure you have a well-structured readme file. :pray:

- [ ] I can see you have `test.md` file in your project. But you should not have any file that is not related to your project in your project. So please kindly remove the `test.md` file from your project. :pray:
- [ ] Please from the project requirement, you should follow one of the [design templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). But as you can see in the screenshot below, your project is not following any of the design templates. Please kindly make sure you follow one of the design templates. :pray:
![Screenshot from 2022-10-28 17-40-08](https://user-images.githubusercontent.com/92303891/198699004-b0bfb46c-ecb6-4dbb-bb51-5ed260192a4d.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 17:48 UTC, Owusu-Desmond commented on index.html
> +           <h4 class="short-presentation">I’m Carlos Philippe </h4>
- [ ] Please Kindly use the `h1` tag for your first headling instead of using `h4`.

2022-10-28 17:48 UTC, Owusu-Desmond commented on .github/workflows/linters.yml
- [ ] Please when following the [html&css](https://github.com/microverseinc/linters-config/blob/master/html-css) linters, your should copy all the codes from this [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) to this file. But you have a few codes in your `linters.yml` which makes checks in this pull request pass some unclean codes that should not be passed.

  I highly suggest you should use the codes this  [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) instead of the one you currently have.

2022-10-28 17:48 UTC, Owusu-Desmond commented on .gitignore
>  test.md
- [ ] Please this `test.md` need to be removed since it has nothing to do with this project

2022-10-28 17:48 UTC, Owusu-Desmond commented on styles.css
> -
- [ ] Please make sure you style your project to stick to one [Figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) provided.

2022-10-28 17:53 UTC, merged